### PR TITLE
Wrap config modules in EventEmitters

### PR DESCRIPTION
**Pull request by ags131**
Implements screeps/screeps#16

### CODE REVIEW

**Comment by ags131** [comment]
Probably not, and as you said, right now theres very few mods published. (I only know of mine and pineapples) 
Would it be worth making the base config object an eventEmitter rather than wrapping each module?

**Comment by ags131** [comment]
I've got forks for the following modules updated on an eventEmitter branch. I haven't had a chance to test them yet, so haven't submitted PRs.

- [ags131/backend-local](https://github.com/ags131/backend-local/tree/eventEmitter)
- [ags131/storage](https://github.com/ags131/storage/tree/eventEmitter)
- [ags131/driver](https://github.com/ags131/driver/tree/eventEmitter)
- [ags131/engine](https://github.com/ags131/engine/tree/eventEmitter)

I think I got all the events, but could have missed one somewhere, this is the list of what I found and updated
```
module.exports = function(config){
  if(config.backend){
    config.backend.on('expressPreConfig',(app)=>{})
    config.backend.on('expressPostConfig',(app)=>{})
    config.backend.on('sendUserNotifications',(user, notifications)=>{})
  }
  if(config.cli){
    config.cli.on('cliSandbox',(sandbox)=>{})
  }
  if(config.engine){
    config.engine.on('init',(processType)=>{})
    config.engine.on('mainLoopStage',(stage)=>{})
    config.engine.on('runnerLoopStage',(stage, userId)=>{})
    config.engine.on('processorLoopStage',(stage, roomId)=>{})
    config.engine.on('playerSandbox',(sandbox, userId)=>{})
    config.engine.on('processObject',(object, roomObjects, roomTerrain, gameTime, roomInfo, objectsUpdate, usersUpdate)=>{}) // set object._skip = true to skip object
    config.engine.on('processObjectIntents',(object, userId, intents, roomObjects, roomTerrain, gameTime, roomInfo, objectsUpdate, usersUpdate)=>{})
    config.engine.on('processRoom',(roomId, roomInfo)=>{})
    config.engine.on('saveRoomHistory',(roomId, baseTime, data)=>{})
  }
}
```

**Comment by ags131** [comment]
Closed since direction has changed towards using emit making this patch no longer relevent

**Comment by artch** [comment]
Looks good!

**Pull request closed without merging**
